name: Build Samsung A04 Kernel (AnyKernel3)

on:
  workflow_dispatch:

jobs:
  build-kernel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          sudo apt update
          sudo apt install -y git ccache flex bison libssl-dev libelf-dev bc build-essential zip curl tar python3

      - name: Run Build Script
        run: |
          chmod +x build_kernel.sh
          ./build_kernel.sh

      - name: Upload AnyKernel3 Zip Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TragicHorizon-v3-r1-A04-AnyKernel3
          path: output/*.zip
